// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.0
// source: search_event.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FaceSearchEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamId  string  `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Timestamp int64   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Faces     []*Face `protobuf:"bytes,3,rep,name=faces,proto3" json:"faces,omitempty"`
}

func (x *FaceSearchEvent) Reset() {
	*x = FaceSearchEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaceSearchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceSearchEvent) ProtoMessage() {}

func (x *FaceSearchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_search_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceSearchEvent.ProtoReflect.Descriptor instead.
func (*FaceSearchEvent) Descriptor() ([]byte, []int) {
	return file_search_event_proto_rawDescGZIP(), []int{0}
}

func (x *FaceSearchEvent) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *FaceSearchEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FaceSearchEvent) GetFaces() []*Face {
	if x != nil {
		return x.Faces
	}
	return nil
}

var File_search_event_proto protoreflect.FileDescriptor

var file_search_event_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x1a, 0x0a, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70,
	0x0a, 0x0f, 0x46, 0x61, 0x63, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x22, 0x0a, 0x05,
	0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x61, 0x63, 0x65, 0x52, 0x05, 0x66, 0x61, 0x63, 0x65, 0x73,
	0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_search_event_proto_rawDescOnce sync.Once
	file_search_event_proto_rawDescData = file_search_event_proto_rawDesc
)

func file_search_event_proto_rawDescGZIP() []byte {
	file_search_event_proto_rawDescOnce.Do(func() {
		file_search_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_search_event_proto_rawDescData)
	})
	return file_search_event_proto_rawDescData
}

var file_search_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_search_event_proto_goTypes = []any{
	(*FaceSearchEvent)(nil), // 0: search_event.FaceSearchEvent
	(*Face)(nil),            // 1: common.Face
}
var file_search_event_proto_depIdxs = []int32{
	1, // 0: search_event.FaceSearchEvent.faces:type_name -> common.Face
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_search_event_proto_init() }
func file_search_event_proto_init() {
	if File_search_event_proto != nil {
		return
	}
	file_face_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_search_event_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FaceSearchEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_search_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_search_event_proto_goTypes,
		DependencyIndexes: file_search_event_proto_depIdxs,
		MessageInfos:      file_search_event_proto_msgTypes,
	}.Build()
	File_search_event_proto = out.File
	file_search_event_proto_rawDesc = nil
	file_search_event_proto_goTypes = nil
	file_search_event_proto_depIdxs = nil
}
