// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package sqlcmain

import (
	"context"
)

// iteratorForCreateBulkEnrollmentFiles implements pgx.CopyFromSource.
type iteratorForCreateBulkEnrollmentFiles struct {
	rows                 []CreateBulkEnrollmentFilesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBulkEnrollmentFiles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBulkEnrollmentFiles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Prime,
		r.rows[0].SessionID,
		r.rows[0].Path,
	}, nil
}

func (r iteratorForCreateBulkEnrollmentFiles) Err() error {
	return nil
}

func (q *Queries) CreateBulkEnrollmentFiles(ctx context.Context, arg []CreateBulkEnrollmentFilesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"EnrollmentSessionFile"}, []string{"prime", "session_id", "path"}, &iteratorForCreateBulkEnrollmentFiles{rows: arg})
}
