// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: person.sql

package sqlcmain

import (
	"context"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO "Person" (prime, first_name, last_name) 
VALUES ($1, $2, $3) 
RETURNING id, prime, first_name, last_name, created_at
`

func (q *Queries) CreatePerson(ctx context.Context, prime string, firstName string, lastName string) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson, prime, firstName, lastName)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Prime,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}
